apiVersion: v1
kind: Service
metadata:
  annotations:
    description: __CI_PROJECT_PATH_SLUG__
  labels:
    app: __CI_PROJECT_PATH_SLUG__
    ref: __CI_ENVIRONMENT_SLUG__
  name: __CI_PROJECT_PATH_SLUG__
spec:
  ports:
    - name: 80-80-tcp
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: __CI_PROJECT_PATH_SLUG__
    ref: __CI_ENVIRONMENT_SLUG__
  type: ClusterIP
